# Generated by Django 2.2.1 on 2020-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpicture',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
