# Generated by Django 2.2.1 on 2020-06-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0002_lessonpicture_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='school_class',
            new_name='subject',
        ),
    ]
